---
kind: pipeline
type: docker
name: python39

steps:
- name: build
  image: python:3.9-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config git
  - pip install -r requirements-dev.txt

---
kind: pipeline
type: docker
name: python38

steps:
- name: build
  image: python:3.8-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config git
  - pip install -r requirements-dev.txt

---
kind: pipeline
type: docker
name: python37

steps:
- name: build
  image: python:3.7-slim
  commands:
  - id
  - python -V
  - apt update && apt install -y gcc g++ libicu-dev pkg-config git
  - pip install -r requirements-dev.txt

# vim: ts=2 sw=2 et
